export interface addMerchantStateRequest {
    selectedFile: string,
    selectedProfileFile:string,
      selectedProofFile: string,
      selectedDocumentFile: string,
      firstname: string,
      firstnameerror: string,
      lastname: string,
      lastnameerror: string,
      email: string,
      emailerror: string,
      mobilenumber: string,
      mobilenumbererror: string,
      shopname: string,
      shopnamerror: string,
      address: string,
      addresserror: string,
      city: string,
      cityerror: string,
      user: string,
      usererror: string,
      zipcode: string,
      zipcodeerror: string,
      latitude: string,
      latitudeerror: string,
      longitude: string,
      longitudeerror: string,
      website: string,
      shoppingpolicy: string,
      shoppingpolicyerror: string,
      refundpolicy: string,
      refundpolicyerror: string,
      cancellationpolicy: string,
      cancellationpolicyerror: string,
      isOpen: boolean,
      checked: boolean,
      selectedFileerror: string,
      selectedProofFileerror: string,
      selectedDocumentFileerror: string,
      selectedProfileFileerror:string,
      password: string,
      passworderror: string,
      citydata: any,
      type: string,
      file: string,
      filetrue: boolean,
      file1: string,
      file1true: boolean,
      file2: string,
      file2true: boolean,
      file4: string,
      file4true: boolean,
      updateTrue: boolean,
      token: string,
      merchantId: string,
      roleid:string,
      roleiderror:string,
      roledata:any
}