export default {
    account: 'Login to Account',
    loginpage: 'Please enter your email and password to continue',
    signin: 'Sign In',
    email: 'Email Address',
    password: 'Password',
    confirm: 'Confirm Your Email',
    name: 'Your Name',
    login: 'Log In',
    signup: 'Create Account',
    signuppage:'Please enter personal information to continue',
    forgotpassword: 'Forgot Password?',
    notmember: 'Do Not have an account?',
    register: 'Register',
    back: 'Back To Login',
    forgot: 'Forgot Password?',
    reset:'Forgot Password',
    dashboard: 'Dashboard',
    home: 'Home',
    about: 'About',
    service: 'Service',
    logout: 'Logout',
    apiUrl: 'https://courier.digitalvichar.in/api/v1/',
    headers: {
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTkzNjgwMzc1LCJleHAiOjE1OTM2ODc1NzV9.jc1NOHGWLgaeqra6RMM71vhIHSFf1GNUbvob66Wip4c',
        apikey: 'courierservice-0000-9876-5432-10@@',
        'Access-Control-Allow-Origin': true
    },
    firstname:'Firstname',
    lastname:'Lastname',

    dashboardTitle: 'Dashboard',
    userTitle: 'User Management',
    addUserTitle: 'Add User',
    viewUserTitle: 'View User',
    userRoleTitle: 'Role Management',
    viewUserRoleTitle: 'View Role',
    adduserRoleTitle: 'Add Role',
    rolePrivilegesTitle: 'Role Privileges',
    countryTitle: 'Country Management',
    stateTitle:'State Management',
    cityTitle:'City Management',
    addCountryTitle:'Add Country',
    addStateTitle:'Add State',
    addCityTitle:'Add City',
    viewCityTitle:'View City',
    viewStateTitle:'View State',
    viewCountryTitle:'View Country',
    categoryTitle:'Category Management',
    addCategoryTitle:'Add Category',
    viewCategoryTitle:'View Category',
    subcategoryTitle:'Sub Category Management',
    addSubCategoryTitle:'Add SubCategory',
    viewSubCategoryTitle:'View SubCategory',
    profileTitle:'Profile',
    loginTitle:'Login',
    signupTitle:'Signup',
    couponManagement:'Coupon Management',
    merchantManagement:'Merchant Management',
    merchantBusinessManagement:'Merchant Business Management',
    merchantReviewManagement:'Merchant Review Management',
    viewProductManagement:'View Product',
    listProduct:'List Product',
    addProduct:'Add Product',
    imageProduct:'Image Product',
    inventoryProduct:'Inventory Product',
    reviewProduct:'Review Product',
    addonProduct:'AddOn Product',
    delivery:'Delivery Mnagement',
    addDelivery:'Add Delivery',
    viewDelivery:'View Delivery',

    userTableColumn: [
        'Name','Email','Number','Address','Status','Action'
    ],
    roleTableColumn: [
        'Role Name','Status','Action'
    ],
    // roleTableColumn: [
    //     'Role Name','Status','Action'
    // ],

}