export default {
    account: 'Login to Account',
    loginpage: 'Please enter your email and password to continue',
    signin: 'Sign In',
    email: 'Email Address',
    password: 'Password',
    confirm: 'Confirm Your Email',
    name: 'Your Name',
    login: 'Log In',
    signup: 'Create Account',
    signuppage:'Please enter personal information to continue',
    forgotpassword: 'Forgot Password?',
    notmember: 'Do Not have an account?',
    register: 'Register',
    back: 'Back To Login',
    forgot: 'Forgot Password?',
    reset:'Forgot Password',
    dashboard: 'Dashboard',
    home: 'Home',
    about: 'About',
    service: 'Service',
    logout: 'Logout',
    apiUrl: 'https://courier.digitalvichar.in/api/v1/',
    headers: {
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTkzNjgwMzc1LCJleHAiOjE1OTM2ODc1NzV9.jc1NOHGWLgaeqra6RMM71vhIHSFf1GNUbvob66Wip4c',
        apikey: 'courierservice-0000-9876-5432-10@@',
        'Access-Control-Allow-Origin': true
    },
    firstname:'Firstname',
    lastname:'Lastname'
}