export interface createCouponStateRequest {
    checked: boolean,
    couponcode: string,
    couponcodeerror: string,
    percentage: number,
    percentageerror: string,
    discountprice: string,
    discountpriceerror: string,
    startdate: string,
    startdateerror: string,
    enddate: string,
    enddateerror: string,
    discription: string,
    discriptionerror: string,
    minamountorder: string,
    minamountordererror: string,
    title: string,
    titleerror: string,
    isByPrice: boolean,
    isActive: boolean,
    updateTrue: boolean,
    couponId: string,
    dpriceFlag: boolean,
    finalprice: string
}