export interface addProfileStateRequest {
    selectedFile: string,
    firstname: string,
    firstnameerror: string,
    lastname: string,
    lastnameerror: string,
    email: string,
    emailerror: string,
    mobilenumber: string,
    mobilenumbererror: string,
    selectedFileerror: string,
    role: string,
    roleerror: string,
    roleid: number,
    roleiderror: string,
    userid: number,
    userrole: any,
    updateTrue: boolean,
    filetrue: boolean,
    file: string,
}
