export interface addProductStateRequest {
    merchantid: string,
    merchantiderror: string,
    maincategoryid: string,
    maincategoryiderror: string,
    subcategoryid: string,
    subcategoryiderror: string,
    productname: string,
    productnameerror: string,
    productdescription: string,
    productdescriptionerror: string,
    price: string,
    priceerror: string,
    discountprice: string,
    discountpriceerror: string,
    isFeatured: boolean,
    metatitle: string,
    metatitleerror: string,
    metadiscription: string,
    metadiscriptionerror: string,
    metakeyword: string,
    metakeyworderror: string,
    sortorder: string,
    sortordererror: string,
    images: any,
    imageserror: string,
    imagesPreviewUrls: any,
    updateTrue: boolean,
    productid: string,
    categorylist: any,
    merchantlist: any,
    productpreview:any,
    newImageUpdatedArray:any
}